### ISSUE TITLE
Update fails due to cache not clean

### ISSUE THREAD

**Issue by javiexin** [BoardTools/upload#41]
Hi,

I have noticed a bug in Upload Extension, when updating certain extension(s) due to some missing cache cleanup (or that is at least what I think).

What I did:

1. I had installed "Change Post Time" extension 1.0.0 from the CDB (https://www.phpbb.com/customise/db/extension/change_post_time/)
2. Removed the extension (Disabled, Delete-data, Cleanup)
3. Uploaded new version 1.0.1 from GitHub (https://github.com/javiexin/chgposttime)
4. Trying to enable, it gives an unspecific error; no way to enable
5. Purge board cache
6. Enable now works fine through Upload Extension

I am using the latest version from GitHub, for 3.2 (develop-3.2.0 branch).

The one thing that strikes me as a possible source of conflict is the fact that CPT 1.0.0 included an emptly ext.php file, and version 1.0.1 removed this useless/unneeded file.

The upgrade process through core Extension Manager works just fine.

Let me know if I can be of help.
-javiexin

**Comment by lavigor** [comment]
@javiexin yes, I'm aware that such a problem can exist because I also encountered it with my QuickReply Reloaded extension exactly after `ext.php` has been removed.
I just didn't have enough time to explore this issue because it seems that cache is automatically cleaned by core enabling/disabling extension functions. `ext.php` should be probably handled as a special case.

I even thought about adding 'Clean cache' button to Upload Extensions, but I'll be very glad for any help with such an issue.

**Comment by javiexin** [comment]
If you tell me where to start (your uses of cache or other places where you use/may use ext.php), I will be happy to help!

**Comment by lavigor** [comment]
@javiexin the reason is that this file is not used directly by Upload Extensions.
When I was exploring the issue (~2 years ago) I supposed that [this line](https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/extension/manager.php#L306) can empty not the whole cache or something like that.
That line should be executed for each extension update process as it disables the extension at first [here](https://github.com/BoardTools/upload/blob/develop-3.2.0/includes/upload/extension.php#L217).
Hmm... I think that when an extension is already disabled, `ext.php` should not be cached and influence the board, or no? Haven't checked that, but UE does not clean the cache if an extension is already disabled/uninstalled.

Enabling is done by [this function in UE](https://github.com/BoardTools/upload/blob/develop-3.2.0/includes/functions/extensions.php#L278).

I'll try to investigate that problem when I have more time, any help is much appreciated.

**Comment by javiexin** [comment]
I will look into it myself as well.  If I find anything, I will report back.
Thanks

**Comment by javiexin** [comment]
I have been looking at this in detail, and I have ruled out the phpbb cache as a source of error.

I am more inclined to think that it has to do with the fact that you are running all updates through ajax/javascript, and hence, not all classes are reloaded properly.  I am suspecting that it has to do with the PHP autoloading and class cache.

However, my limited knowledge about ajax does not allow me to properly debug the code.  So, I think I will give up for now.  Anyhow, if there is something I can do, let me know.

**Comment by javiexin** [comment]
Just to be more precise, and to give you more hints (when you have time).
The error ONLY happens if you install the extension WITHOUT previously removing the files from the file system (Delete Extension in UE).  And once you get the error, it will persist, until you do clean the phpBB cache explicitly.  But the cache was cleared fine when it should (on disable/delete data of the previous version).
I am suspecting something to do with the upload AND creation of zip file for the previous version (somewhere in `upload/includes/upload/extension.php`), together with some PHP autoload and class cache issues.  But I cannot confirm...

**Comment by javiexin** [comment]
I think I found the cause of this issue. It is, in fact, due to an internal PHP cache of file statuses.
As you are running through javascript/ajax, this is not cleared when needed.
You should call this function: http://php.net/manual/en/function.clearstatcache.php when you change the filesystem, and maybe also when you clear the phpBB cache.
Let me know ir that helped.

**Comment by lavigor** [comment]
It turned out that there is no way to unload the previously registered class.
That is why `class_exists` returns `true`, but phpBB's extension manager relies on it.
I put the cache purging statement after the details page function call.

Thank you for collaboration!

**Comment by lavigor** [comment]
Hmm... I've found that `clearstatcache` does not work as expected.
Or maybe I misunderstand the time period when PHP actually removes files.

However the issue remains fixed. Just experimenting with that function.
